updated with whatever the f happened here over the years

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,4 +1,4 @@
-# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
+#Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
 # Initialization code that may require console input (password prompts, [y/n]
 # confirmations, etc.) must go above this block; everything else may go below.
 if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
@@ -6,17 +6,17 @@ if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]
 fi
 
 # If you come from bash you might have to change your $PATH.
- export PATH=$HOME/bin:/usr/local/bin:$PATH
+export PATH=$HOME/bin:/usr/local/bin:$PATH
 
 # Path to your oh-my-zsh installation.
 export ZSH="$HOME/.oh-my-zsh"
 
 # Uncomment the following line to use case-sensitive completion.
- CASE_SENSITIVE="true"
+#CASE_SENSITIVE="true"
 
 # Uncomment the following line to use hyphen-insensitive completion.
 # Case-sensitive completion must be off. _ and - will be interchangeable.
- HYPHEN_INSENSITIVE="true"
+HYPHEN_INSENSITIVE="true"
 
 # Uncomment one of the following lines to change the auto-update behavior
 # zstyle ':omz:update' mode disabled  # disable automatic updates
@@ -36,7 +36,7 @@ zstyle ':omz:update' frequency 13
 # DISABLE_AUTO_TITLE="true"
 
 # Uncomment the following line to enable command auto-correction.
- ENABLE_CORRECTION="true"
+ENABLE_CORRECTION="true"
 
 # Uncomment the following line to display red dots whilst waiting for completion.
 # You can also set it to another string to have that shown instead of the default red dots.
@@ -65,7 +65,7 @@ HIST_STAMPS="dd/mm/yyyy"
 # Custom plugins may be added to $ZSH_CUSTOM/plugins/
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
-plugins=(git fzf-zsh-plugin colored-man-pages ssh-agent macos zsh-syntax-highlighting)
+plugins=(git fzf-zsh-plugin colored-man-pages ssh-agent macos zsh-syntax-highlighting asdf)
 
 
 source $ZSH/oh-my-zsh.sh
@@ -73,6 +73,8 @@ source $ZSH/oh-my-zsh.sh
 # User configuration
 
 export MANPATH="/usr/local/man:$MANPATH"
+export EDITOR="vim"
+export GOPATH="${HOME}/go"
 
 # You may need to manually set your language environment
 export LANG=en_US.UTF-8
@@ -99,13 +101,88 @@ alias edit_ohmyzsh="$EDITOR ~/.oh-my-zsh"
 
 # SSH Agent configuration
 zstyle :omz:plugins:ssh-agent agent-forwarding on
-zstyle :omz:plugins:ssh-agent identities id_rsa id_ed25519
+zstyle :omz:plugins:ssh-agent identities id_rsa id_ed25519 hiniko_github
 zstyle :omz:plugins:ssh-agent lifetime 4h
 
 # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
 source /opt/homebrew/opt/powerlevel10k/powerlevel10k.zsh-theme
 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
 
+
 # Setup dir env
 eval "$(direnv hook zsh)"
 
+# Setup Pyenv
+export PATH="${HOME}/.pyenv/bin:${PATH}"
+eval "$(pyenv init --path)"
+eval "$(pyenv virtualenv-init -)"
+
+# add bins to path 
+export PATH="${HOME}/go/bin:${HOME}/flutter/bin:$PATH"
+# add android studio bins to path
+export PATH="${HOME}/Library/Android/sdk/cmdline-tools/latest/bin:$PATH"
+# Add dart bins to path
+export PATH="$PATH:$HOME/.pub-cache/bin"
+
+
+docker-cleanup () { docker rm -f $(docker ps -a -q); }
+
+# VS code open function
+code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
+
+toolstrap () { imp-tool sync state && imp-tool sync contents ; }
+
+# Nice netstat function
+macnst (){
+    netstat -Watnlv | grep LISTEN | awk '{"ps -o comm= -p " $9 | getline procname;colred="\033[01;31m";colclr="\033[0m"; print colred "proto: " colclr $1 colred " | addr.port: " colclr $4 colred " | pid: " colclr $9 colred " | name: " colclr procname;  }' | column -t -s "|";
+}
+
+x86-shell () { arch -x86_64 /bin/zsh ; }
+
+# The next line updates PATH for the Google Cloud SDK.
+if [ -f '/Users/shermanrose/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/shermanrose/Downloads/google-cloud-sdk/path.zsh.inc'; fi
+
+# The next line enables shell command completion for gcloud.
+if [ -f '/Users/shermanrose/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/shermanrose/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
+
+# >>> conda initialize >>>
+# !! Contents within this block are managed by 'conda init' !!
+__conda_setup="$('/Users/shermanrose/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
+if [ $? -eq 0 ]; then
+    eval "$__conda_setup"
+else
+    if [ -f "/Users/shermanrose/anaconda3/etc/profile.d/conda.sh" ]; then
+        . "/Users/shermanrose/anaconda3/etc/profile.d/conda.sh"
+    else
+        export PATH="/Users/shermanrose/anaconda3/bin:$PATH"
+    fi
+fi
+unset __conda_setup
+# <<< conda initialize <<<
+
+# NVM Setup
+export NVM_DIR="$HOME/.nvm"
+[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
+[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
+
+alias gam="/Users/shermanrose/bin/gam/gam"
+
+alias yeet='yeeet() {
+    selected_files=($(git status -s | fzf --multi --ansi | awk "{print \$2}" | tr "\n" "\0" | xargs -0))
+
+    if [ -z "$selected_files" ]; then
+        echo "No files selected."
+    else
+        echo -n "Enter commit message: "
+        read commit_message
+        if [ -z "$commit_message" ]; then
+            echo "Commit message cannot be empty."
+        else
+            for file in $selected_files; do
+                git add "$file"
+            done
+            git commit -m "$commit_message" && \
+            git push -u origin HEAD
+        fi
+    fi
+}; yeeet'
