rebased from io version

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -65,7 +65,7 @@ HIST_STAMPS="dd/mm/yyyy"
 # Custom plugins may be added to $ZSH_CUSTOM/plugins/
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
-plugins=(git fzf-zsh-plugin colored-man-pages ssh-agent macos zsh-syntax-highlighting asdf)
+plugins=(zsh-vi-mode git fzf-zsh-plugin colored-man-pages ssh-agent macos zsh-syntax-highlighting asdf)
 
 ZSH_THEME="powerlevel10k/powerlevel10k"
 
@@ -88,11 +88,6 @@ alias vim='nvim'
 
 export FZF_DEFAULT_OPTS="--layout=reverse --info=inline --height=80% --multi --preview='([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2>/dev/null | head -n 200' --preview-window=':hidden' --color='hl:148,hl+:154,pointer:032,marker:010,bg+:237,gutter:008' --prompt='∼ ' --pointer='▶' --marker='✓' --bind '?:toggle-preview' --bind 'ctrl-a:select-all' --bind 'ctrl-e:execute(vim {+} >/dev/tty)' --bind 'ctrl-v:execute(code {+})' --bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'"
 
-# Setup dir env
-eval "$(direnv hook zsh)"
-
-# Setup FZF keybindings
-eval "$(fzf --zsh)"
 
 zshrc_path="${HOME}/.dotfiles/zsh/"
 
@@ -105,6 +100,9 @@ source "${zshrc_path}/aliases/macos.zsh"
 source "${zshrc_path}/aliases/p10k.zsh"
 source "${zshrc_path}/settings/ssh-agent.zsh"
 
+export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin"
+export FZF_DEFAULT_OPTS="--layout=reverse --info=inline --height=80% --multi --preview='([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2>/dev/null | head -n 200' --preview-window=':hidden' --color='hl:148,hl+:154,pointer:032,marker:010,bg+:237,gutter:008' --prompt='∼ ' --pointer='▶' --marker='✓' --bind '?:toggle-preview' --bind 'ctrl-a:select-all' --bind 'ctrl-e:execute(vim {+} >/dev/tty)' --bind 'ctrl-v:execute(code {+})' --bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'"
+
 # Personal Includes
 if [[ "$hostname" == "saki.local" ]]; then
     
@@ -112,8 +110,31 @@ fi
 
 # Work includes
 if [[ "$hostname" == "shermanrose-mac-xh4fnh2g7y.corp.improbable.io" ]]; then
-    source "${zshrc_path}/aliases/flutter.zsh"
-    source "${zshrc_path}/aliases/gam.zsh"
     source "${zshrc_path}/aliases/gcloud.zsh"
-    source "${zshrc_path}/aliases/nvm.zsh"
 fi
+
+alias yeet='yeeet() {
+    selected_files=($(git status -s | fzf --multi --ansi | awk "{print \$2}" | tr "\n" "\0" | xargs -0))
+
+    if [ -z "$selected_files" ]; then
+        echo "No files selected."
+    else
+        echo -n "Enter commit message: "
+        read commit_message
+        if [ -z "$commit_message" ]; then
+            echo "Commit message cannot be empty."
+        else
+            for file in $selected_files; do
+                git add "$file"
+            done
+            git commit -m "$commit_message" && \
+            git push -u origin HEAD
+        fi
+    fi
+}; yeeet'
+
+# Setup dir env
+eval "$(direnv hook zsh)"
+
+# Setup FZF keybindings
+eval "$(fzf --zsh)"
